services:
  - type: web
    name: laswo-studios
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "python manage.py migrate && gunicorn laswo_studios.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: laswo-studios-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4

databases:
  - name: laswo-studios-db
    plan: free